version: "3"

volumes:
  dbdata:

services:
  # Web Server
  webserver:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/webserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/webserver/nginx/www.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/application
      - ./docker/webserver/public/robots.disallow.txt:/application/public/robots.txt:ro
    environment:
      - VIRTUAL_HOST=www.innovationowl.com
      - ENABLE_ACME=false
    networks:
      # expose_network:
      net:
    depends_on:
      - php_fpm
    restart: always

  # Web Application
  php_fpm:
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
    volumes:
      - ./docker/webapp/php-ini-overrides.ini:/usr/local/etc/php/conf.d/default.ini:ro
      - ./docker/webapp/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zz-pm.conf:ro
      - ./:/application
      - ./docker/webserver/public/robots.disallow.txt:/application/public/robots.txt:ro
    networks:
      net:
    restart: always

networks:
  # Join proxy network for exposing http services
  # expose_network:
  #   external:
  #     name: web_proxy
  # Internal network for this project
  net:
